#!/usr/bin/env python3
"""
release-efficiency-analysis.py — Post-release efficiency analysis for CEO health checks.

Reconstructs a timeline for the last completed (or a named) release and surfaces
efficiency gaps: redundant dev passes, executor quarantine rate, CEO proxy load,
shipping lag, code-review completion, and Gate R5 delay.

Usage:
  python3 scripts/release-efficiency-analysis.py
  python3 scripts/release-efficiency-analysis.py --release-id 20260412-dungeoncrawler-release-r
  python3 scripts/release-efficiency-analysis.py --json

Exit codes:
  0 — no FAIL-level findings
  1 — one or more FAIL-level findings
"""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from typing import Optional

ROOT = pathlib.Path(__file__).parent.parent

# ── Thresholds ───────────────────────────────────────────────────────────────
THRESH_REDUNDANT_PASSES = 1        # more than this many dev passes → FAIL
THRESH_QUARANTINE_RATE  = 0.25     # >25% quarantine rate → WARN (>50% → FAIL)
THRESH_CEO_PROXY_WARN   = 2        # CEO proxy sessions above this → WARN
THRESH_CEO_PROXY_FAIL   = 5        # CEO proxy sessions above this → FAIL
THRESH_SHIPPING_LAG_WARN_H = 24    # hours from dev-done to push → WARN
THRESH_SHIPPING_LAG_FAIL_H = 72    # hours from dev-done to push → FAIL
THRESH_R5_DELAY_WARN_H  = 1        # Gate R5 should run within 1h of push → WARN
THRESH_R5_DELAY_FAIL_H  = 4        # Gate R5 > 4h post-push → FAIL

# ── Helpers ──────────────────────────────────────────────────────────────────

def parse_iso(s: str) -> Optional[datetime]:
    """Parse an ISO-8601 timestamp, return UTC-aware datetime or None."""
    if not s:
        return None
    s = s.strip().rstrip("Z")
    for fmt in (
        "%Y-%m-%dT%H:%M:%S.%f%z",
        "%Y-%m-%dT%H:%M:%S%z",
        "%Y-%m-%dT%H:%M:%S.%f",
        "%Y-%m-%dT%H:%M:%S",
    ):
        try:
            dt = datetime.strptime(s, fmt)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt
        except ValueError:
            continue
    return None


def mtime_dt(p: pathlib.Path) -> Optional[datetime]:
    """Return the mtime of a file as a UTC-aware datetime."""
    try:
        return datetime.fromtimestamp(p.stat().st_mtime, tz=timezone.utc)
    except OSError:
        return None


def hours_between(a: Optional[datetime], b: Optional[datetime]) -> Optional[float]:
    if a is None or b is None:
        return None
    return (b - a).total_seconds() / 3600


def fmt_hours(h: Optional[float]) -> str:
    if h is None:
        return "unknown"
    if h < 1:
        return f"{h*60:.0f}m"
    if h < 48:
        return f"{h:.1f}h"
    return f"{h/24:.1f}d"


def outbox_status(path: pathlib.Path) -> str:
    """Return the '- Status:' value from an outbox file (lower-cased, stripped)."""
    try:
        for line in path.read_text(errors="ignore").splitlines():
            m = re.match(r"^\s*-\s*[Ss]tatus:\s*(.+)", line)
            if m:
                return m.group(1).strip().lower()
    except OSError:
        pass
    return ""


def active_release_ids() -> set[str]:
    """Return release IDs from tmp/release-cycle-active/*.release_id (last completed)."""
    active_dir = ROOT / "tmp" / "release-cycle-active"
    result: set[str] = set()
    if not active_dir.exists():
        return result
    for f in active_dir.glob("*.release_id"):
        rid = f.read_text(errors="ignore").strip()
        if rid:
            result.add(rid)
    return result


def next_release_ids() -> set[str]:
    """Return release IDs from tmp/release-cycle-active/*.next_release_id (in-progress)."""
    active_dir = ROOT / "tmp" / "release-cycle-active"
    result: set[str] = set()
    if not active_dir.exists():
        return result
    for f in active_dir.glob("*.next_release_id"):
        rid = f.read_text(errors="ignore").strip()
        if rid:
            result.add(rid)
    return result


def find_release_push_time(release_id: str) -> Optional[datetime]:
    """
    Find the push timestamp for a release from PM signoff files.
    Prefer coordinated push signoffs (Timestamp:) over manual ones (Signed off at:)
    since the coordinated push represents the actual production deployment moment.
    """
    coordinated: Optional[datetime] = None
    manual: Optional[datetime] = None

    for signoff in ROOT.glob("sessions/*/artifacts/release-signoffs/*.md"):
        if release_id not in signoff.name:
            continue
        txt = signoff.read_text(errors="ignore")
        # Coordinated push signoff (generated by post-coordinated-push.sh)
        m = re.search(r"Timestamp:\s*(.+)", txt)
        if m:
            dt = parse_iso(m.group(1).strip())
            if dt and (coordinated is None or dt < coordinated):
                coordinated = dt
            continue
        # Manual PM signoff
        m = re.search(r"Signed off at:\s*(.+)", txt)
        if m:
            dt = parse_iso(m.group(1).strip())
            if dt and (manual is None or dt < manual):
                manual = dt

    return coordinated if coordinated is not None else manual


def find_last_completed_release() -> tuple[str, str]:
    """
    Return (release_id, site) of the most recently completed release.

    Uses tmp/release-cycle-active/*.release_id as the canonical source of truth
    (these are the releases that have been pushed to production).  Explicitly
    excludes *.next_release_id values (in-progress, not yet shipped).

    When multiple completed releases exist (e.g. coordinated push), prefer the
    one with the most features — companion/bump releases with 0 features are
    de-prioritized so the analysis targets the release that drove the work.

    Falls back to signoff-timestamp scanning when the active dir is missing.
    """
    in_progress = next_release_ids()
    completed   = active_release_ids() - in_progress

    def _release_score(rid: str) -> tuple[int, float]:
        """Score = (feature_count, push_timestamp_epoch). Higher is better."""
        feat_count = len(features_for_release(rid))
        push_dt = find_release_push_time(rid)
        push_ts = push_dt.timestamp() if push_dt else 0.0
        return (feat_count, push_ts)

    if completed:
        scored = sorted(completed, key=_release_score, reverse=True)
        best_release = scored[0]
        m = re.match(r"\d{8}-(.+)-release-[a-z0-9]+$", best_release)
        best_site = m.group(1) if m else ""
        return best_release, best_site

    # Fallback: scan signoffs, exclude in-progress release IDs
    best_dt: Optional[datetime] = None
    best_release = ""
    best_site = ""
    for signoff in ROOT.glob("sessions/*/artifacts/release-signoffs/*.md"):
        stem = signoff.stem
        if stem in in_progress:
            continue
        id_match = re.match(r"\d{8}-(.+)-release-[a-z0-9]+$", stem)
        if not id_match:
            continue
        site = id_match.group(1)
        txt = signoff.read_text(errors="ignore")
        for pattern in (r"Timestamp:\s*(.+)", r"Signed off at:\s*(.+)"):
            m_ts = re.search(pattern, txt)
            if m_ts:
                dt = parse_iso(m_ts.group(1).strip())
                if dt and (best_dt is None or dt > best_dt):
                    best_dt = dt
                    best_release = stem
                    best_site = site
                break

    return best_release, best_site


def features_for_release(release_id: str) -> list[str]:
    """Return feature IDs whose feature.md points to this release."""
    result = []
    for fmd in ROOT.glob("features/*/feature.md"):
        txt = fmd.read_text(errors="ignore")
        m = re.search(r"[-\s]*[Rr]elease:\s*\n?(20[0-9]+-[^\s\n]+)", txt)
        if m and m.group(1).strip() == release_id:
            feat_id = fmd.parent.name
            result.append(feat_id)
    return sorted(result)


def find_coordinated_co_release(primary_release_id: str) -> tuple[str, str]:
    """
    If primary_release_id was part of a coordinated push, return (co_release_id, co_site).
    Looks for coordinated push signoffs that mention both releases in filename/content.
    """
    for signoff in ROOT.glob("sessions/*/artifacts/release-signoffs/*.md"):
        txt = signoff.read_text(errors="ignore")
        # The orchestrator encodes both IDs in the 'Signed by:' line
        m = re.search(r"coordinated push (.+)__(.+)\)", txt)
        if m:
            ids = [m.group(1).strip(), m.group(2).strip()]
            if primary_release_id in ids:
                other = [x for x in ids if x != primary_release_id]
                if other:
                    other_id = other[0]
                    # Derive site from ID prefix: YYYYMMDD-<site>-release-X
                    parts = other_id.split("-")
                    if len(parts) >= 3:
                        # site is everything between date and 'release-X'
                        site_part = "-".join(parts[1:-2])
                        return other_id, site_part
    return "", ""


def dev_outbox_files_for_feature(feat_id: str, dev_agent: str) -> list[pathlib.Path]:
    """Return all dev outbox .md files that contain the feature ID in filename."""
    outbox = ROOT / "sessions" / dev_agent / "outbox"
    if not outbox.exists():
        return []
    return sorted([f for f in outbox.glob(f"*{feat_id}*.md")])


def agent_outbox_files_for_release(agent: str, release_id: str,
                                   feature_ids: list[str]) -> list[pathlib.Path]:
    """Return outbox files for an agent that reference release_id or any feature_id."""
    outbox = ROOT / "sessions" / agent / "outbox"
    if not outbox.exists():
        return []
    hits = []
    for f in sorted(outbox.glob("*.md")):
        if release_id in f.name:
            hits.append(f)
            continue
        if any(fid in f.name for fid in feature_ids):
            hits.append(f)
    return hits


def count_quarantine(files: list[pathlib.Path]) -> int:
    return sum(1 for f in files if outbox_status(f) in ("needs-info", "blocked"))


def find_r5_audit_time(site: str, push_time: datetime) -> Optional[datetime]:
    """Find the Gate R5 production audit time after push_time."""
    # CEO outbox entries named like *site-audit* or *qa-findings* or *r5*
    ceo_outbox = ROOT / "sessions" / "ceo-copilot-2" / "outbox"
    if not ceo_outbox.exists():
        return None
    # Also check qa-<site> outbox for auto-site-audit artifacts
    candidates: list[pathlib.Path] = []
    for pattern in (
        f"*site-audit*{site}*",
        f"*{site}*audit*",
        f"*gate*r5*",
        f"*r5*audit*",
        f"*qa-findings*{site}*",
        f"*recovery-pass*",
    ):
        candidates += list(ceo_outbox.glob(pattern))
    for qa_outbox in ROOT.glob(f"sessions/qa-{site}/outbox/*.md"):
        if "gate2" in qa_outbox.name or "audit" in qa_outbox.name:
            candidates.append(qa_outbox)
    # Return earliest mtime after push_time
    result = None
    for f in candidates:
        dt = mtime_dt(f)
        if dt and dt > push_time:
            if result is None or dt < result:
                result = dt
    return result


def collect_all_agents(teams_json: pathlib.Path) -> dict[str, str]:
    """Return {agent_id: role} from agents.yaml."""
    agents_yaml = ROOT / "org-chart" / "agents" / "agents.yaml"
    if not agents_yaml.exists():
        return {}
    try:
        import yaml
        data = yaml.safe_load(agents_yaml.read_text(errors="ignore"))
        return {a["id"]: a.get("role", "") for a in data.get("agents", [])}
    except Exception:
        return {}


def find_release_activation_time(release_id: str, pm_agent: str) -> Optional[datetime]:
    """
    Estimate when the release was activated (scope-activated by PM).

    Priority:
      1. File timestamp embedded in a scope-activate outbox filename for this release
         (filename format: YYYYMMDD-HHMMSS-scope-activate-<release_id>.md)
      2. Earliest mtime of any scope-activate outbox file referencing this release
      3. Fallback: tmp/release-cycle-active/<site>.started_at if it still holds this release_id
    """
    pm_outbox = ROOT / "sessions" / pm_agent / "outbox"
    scope_times: list[datetime] = []

    if pm_outbox.exists():
        for f in pm_outbox.glob(f"*scope-activate*{release_id}*"):
            # Prefer embedded timestamp in filename (YYYYMMDD-HHMMSS prefix)
            m = re.match(r"(\d{8})-(\d{6})-", f.name)
            if m:
                try:
                    dt = datetime.strptime(m.group(1) + m.group(2), "%Y%m%d%H%M%S")
                    dt = dt.replace(tzinfo=timezone.utc)
                    scope_times.append(dt)
                    continue
                except ValueError:
                    pass
            dt = mtime_dt(f)
            if dt:
                scope_times.append(dt)

    if scope_times:
        return min(scope_times)

    # Fallback: started_at file (only valid if it still references this release)
    active_dir = ROOT / "tmp" / "release-cycle-active"
    if active_dir.exists():
        site_m = re.match(r"\d{8}-(.+)-release-[a-z0-9]+$", release_id)
        if site_m:
            site_stem = site_m.group(1)
            rid_file = active_dir / f"{site_stem}.release_id"
            started_file = active_dir / f"{site_stem}.started_at"
            if (rid_file.exists() and rid_file.read_text(errors="ignore").strip() == release_id
                    and started_file.exists()):
                dt = parse_iso(started_file.read_text(errors="ignore").strip())
                if dt:
                    return dt

    return None


def ceo_proxy_sessions(release_id: str, feature_ids: list[str],
                        co_release_id: str,
                        push_time: Optional[datetime]) -> dict[str, list[pathlib.Path]]:
    """
    Find CEO outbox entries that represent dev/QA/PM proxy work for this release.

    Matches on filename OR file content (to catch hardening/coverage sessions
    whose filenames use short keywords rather than full feature IDs).
    Returns dict keyed by category: 'dev', 'qa', 'pm', 'other'.
    """
    ceo_outbox = ROOT / "sessions" / "ceo-copilot-2" / "outbox"
    if not ceo_outbox.exists():
        return {}
    result: dict[str, list] = defaultdict(list)
    dev_patterns = re.compile(r"impl|hardening|exposure|coverage|defect|fix")
    qa_patterns  = re.compile(r"preflight|gate2|qa-findings|unit-test|syshealth|audit")
    pm_patterns  = re.compile(r"signoff|scope.activate|groom|coordinated")

    # Build keyword set: full feature IDs + short slugs (last segment after dc-cr- / feature-)
    keywords = set()
    keywords.add(release_id.lower())
    if co_release_id:
        keywords.add(co_release_id.lower())
    for fid in feature_ids:
        keywords.add(fid.lower())
        # Also add the last meaningful segment (e.g. "snares", "chameleon", "survival")
        parts = fid.lower().split("-")
        if len(parts) >= 2:
            keywords.add(parts[-1])
            keywords.add("-".join(parts[-2:]))

    for f in sorted(ceo_outbox.glob("*.md")):
        name = f.name.lower()

        # Fast path: filename match
        name_match = any(kw in name for kw in keywords)

        # Content match (only read if filename didn't match — avoids reading all files)
        if not name_match:
            try:
                content = f.read_text(errors="ignore").lower()
                name_match = (
                    release_id.lower() in content
                    or any(fid.lower() in content for fid in feature_ids)
                )
                # If content matched, use filename for category, fall through below
                if not name_match:
                    continue
            except OSError:
                continue

        if dev_patterns.search(name):
            result["dev"].append(f)
        elif qa_patterns.search(name):
            result["qa"].append(f)
        elif pm_patterns.search(name):
            result["pm"].append(f)
        else:
            result["other"].append(f)
    return dict(result)


# ── Output helpers ────────────────────────────────────────────────────────────

PASS = "✅ PASS"
FAIL = "❌ FAIL"
WARN = "⚠️  WARN"
INFO = "   ℹ️ "

fail_count = 0
warn_count = 0
findings: list[tuple[str, str]] = []


def emit(level: str, msg: str) -> None:
    global fail_count, warn_count
    print(f"{level}  {msg}")
    findings.append((level.strip(), msg))
    if "FAIL" in level:
        fail_count += 1
    elif "WARN" in level:
        warn_count += 1


def hr() -> None:
    print("────────────────────────────────────────────────────────")


def section(title: str) -> None:
    print()
    print(f"── {title} ──")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--release-id", default="")
    parser.add_argument("--site", default="")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    os.chdir(ROOT)

    # ── 1. Resolve release ───────────────────────────────────────────────────
    release_id = args.release_id.strip()
    site = args.site.strip()

    if not release_id:
        release_id, site = find_last_completed_release()

    if not release_id:
        print("⚠️  WARN  release-efficiency-analysis: no completed release signoffs found")
        return 0

    # Derive site from release_id if not provided
    if not site:
        m = re.match(r"\d{8}-(.+)-release-[a-z0-9]+$", release_id)
        if m:
            site = m.group(1)

    push_time = find_release_push_time(release_id)
    co_release_id, co_site = find_coordinated_co_release(release_id)

    # Resolve product team agents
    teams_json = ROOT / "org-chart" / "products" / "product-teams.json"
    dev_agent = f"dev-{site}"
    pm_agent  = f"pm-{site}"
    qa_agent  = f"qa-{site}"
    if teams_json.exists():
        try:
            data = json.loads(teams_json.read_text(errors="ignore"))
            for t in data.get("teams", []):
                if t.get("id") == site:
                    dev_agent = t.get("dev_agent", dev_agent)
                    pm_agent  = t.get("pm_agent", pm_agent)
                    qa_agent  = t.get("qa_agent", qa_agent)
                    break
        except Exception:
            pass

    feature_ids = features_for_release(release_id)

    # ── 2. Header ────────────────────────────────────────────────────────────
    print()
    print("═══════════════════════════════════════════════════════")
    print("  Release Efficiency Analysis")
    print(f"  {datetime.now(tz=timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")
    print("═══════════════════════════════════════════════════════")
    print(f"  Release:    {release_id}  ({site})")
    if co_release_id:
        print(f"  Co-release: {co_release_id}  ({co_site})")
    print(f"  Push:       {push_time.strftime('%Y-%m-%dT%H:%M:%SZ') if push_time else 'unknown'}")
    print(f"  Features:   {len(feature_ids)}")
    if feature_ids:
        for fid in feature_ids:
            print(f"              • {fid}")

    # ── 3. Dev pass analysis ─────────────────────────────────────────────────
    section("Dev Pass Analysis")

    dev_files_by_feature: dict[str, list[pathlib.Path]] = {}
    all_dev_mtimes: list[datetime] = []
    total_passes = 0
    redundant_features: list[str] = []

    for feat_id in feature_ids:
        files = dev_outbox_files_for_feature(feat_id, dev_agent)
        dev_files_by_feature[feat_id] = files
        total_passes += len(files)
        if len(files) > THRESH_REDUNDANT_PASSES:
            redundant_features.append(feat_id)
        for f in files:
            dt = mtime_dt(f)
            if dt:
                all_dev_mtimes.append(dt)

    dev_start = min(all_dev_mtimes) if all_dev_mtimes else None
    dev_done  = max(all_dev_mtimes) if all_dev_mtimes else None

    print(f"  Features dispatched to {dev_agent}: {len(feature_ids)}")
    print(f"  Total dev outbox files (all passes): {total_passes}")

    for feat_id in feature_ids:
        files = dev_files_by_feature.get(feat_id, [])
        flag = "⚠️ " if len(files) > THRESH_REDUNDANT_PASSES else "  "
        print(f"  {flag} {feat_id}: {len(files)} pass(es)")

    if redundant_features:
        emit(FAIL, f"Redundant dev passes: {len(redundant_features)} feature(s) re-dispatched "
             f"after already done — {', '.join(redundant_features)}")
    else:
        emit(PASS, "Dev passes: no redundant re-dispatches detected")

    # ── 4. Timeline ──────────────────────────────────────────────────────────
    section("Process Flow Timing")

    activation_time = find_release_activation_time(release_id, pm_agent)
    active_cycle    = hours_between(activation_time, push_time)
    shipping_lag    = hours_between(dev_done, push_time)

    print(f"  {'Stage':<42} {'Duration':<12}")
    print(f"  {'-'*42} {'-'*12}")
    print(f"  {'Feature dev start → dev done':<42} {fmt_hours(hours_between(dev_start, dev_done)):<12}")
    print(f"  {'Dev done → production push (shipping lag)':<42} {fmt_hours(shipping_lag):<12}")
    print(f"  {'Release activation → push (active cycle)':<42} {fmt_hours(active_cycle):<12}")

    if push_time:
        r5_time = find_r5_audit_time(site, push_time)
        r5_delay = hours_between(push_time, r5_time)
        print(f"  {'Gate R5 post-push delay':<42} {fmt_hours(r5_delay):<12}")
    else:
        r5_delay = None

    if shipping_lag is not None:
        if shipping_lag > THRESH_SHIPPING_LAG_FAIL_H:
            emit(FAIL, f"Shipping lag: {fmt_hours(shipping_lag)} from dev-done to push "
                 f"(threshold: {THRESH_SHIPPING_LAG_FAIL_H}h)")
        elif shipping_lag > THRESH_SHIPPING_LAG_WARN_H:
            emit(WARN, f"Shipping lag: {fmt_hours(shipping_lag)} from dev-done to push "
                 f"(threshold: {THRESH_SHIPPING_LAG_WARN_H}h)")
        else:
            emit(PASS, f"Shipping lag: {fmt_hours(shipping_lag)} — within threshold")

    if r5_delay is not None:
        if r5_delay > THRESH_R5_DELAY_FAIL_H:
            emit(FAIL, f"Gate R5 delay: {fmt_hours(r5_delay)} post-push "
                 f"(threshold: {THRESH_R5_DELAY_FAIL_H}h)")
        elif r5_delay > THRESH_R5_DELAY_WARN_H:
            emit(WARN, f"Gate R5 delay: {fmt_hours(r5_delay)} post-push "
                 f"(threshold: {THRESH_R5_DELAY_WARN_H}h)")
        else:
            emit(PASS, f"Gate R5 delay: {fmt_hours(r5_delay)} — within threshold")
    else:
        emit(WARN, "Gate R5 audit time could not be determined")

    # ── 5. Agent activation & quarantine rate ────────────────────────────────
    section("Agent Activation & Executor Health")

    # Gating agents whose quarantine rate is individually checked
    gating_agents = {pm_agent, "agent-code-review"}
    if co_release_id and co_site:
        gating_agents.add(f"pm-{co_site}")

    check_agents = [dev_agent, pm_agent, qa_agent, "ceo-copilot-2", "agent-code-review"]
    if co_release_id and co_site:
        co_pm = f"pm-{co_site}"
        if co_pm not in check_agents:
            check_agents.append(co_pm)

    print(f"  {'Agent':<26} {'Sessions':>8} {'Quarantined':>12} {'Rate':>8}  Status")
    print(f"  {'-'*26} {'--------':>8} {'----------':>12} {'----':>8}  ------")

    total_sessions = 0
    total_quarantined = 0
    gating_quarantine_fails: list[str] = []

    for agent in check_agents:
        files = agent_outbox_files_for_release(agent, release_id, feature_ids)
        n = len(files)
        q = count_quarantine(files)
        rate = q / n if n > 0 else 0.0
        total_sessions += n
        total_quarantined += q

        if n == 0:
            status = "no activity"
            flag = "   "
        elif rate >= 0.5:
            status = "❌ majority quarantined"
            flag = "❌ "
            if agent in gating_agents:
                gating_quarantine_fails.append(f"{agent} ({q}/{n} = {rate:.0%})")
        elif rate >= THRESH_QUARANTINE_RATE:
            status = "⚠️  partial quarantine"
            flag = "⚠️  "
        elif q > 0:
            status = f"⚠️  {q} quarantined"
            flag = "⚠️  "
        else:
            status = "✅ clean"
            flag = "   "

        print(f"  {flag}{agent:<24} {n:>8} {q:>12} {rate:>7.0%}  {status}")

    # Global quarantine rate
    global_rate = total_quarantined / total_sessions if total_sessions > 0 else 0.0
    print(f"  {'TOTAL':<26} {total_sessions:>8} {total_quarantined:>12} {global_rate:>7.0%}")

    # Per-gating-agent FAIL takes priority over global rate
    if gating_quarantine_fails:
        emit(FAIL, f"Gating agent(s) majority-quarantined: {', '.join(gating_quarantine_fails)} "
             f"— release gates bypassed by executor failure")
    elif global_rate > 0.5:
        emit(FAIL, f"Executor quarantine rate: {global_rate:.0%} of all sessions "
             f"({total_quarantined}/{total_sessions}) — systemic executor failure")
    elif global_rate > THRESH_QUARANTINE_RATE:
        emit(WARN, f"Executor quarantine rate: {global_rate:.0%} of agent sessions "
             f"({total_quarantined}/{total_sessions})")
    else:
        emit(PASS, f"Executor quarantine rate: {global_rate:.0%} — within threshold")

    # Code review gate
    cr_files = agent_outbox_files_for_release("agent-code-review", release_id, feature_ids)
    cr_done = sum(1 for f in cr_files if outbox_status(f) in ("done", "approved", "approve"))
    cr_total = len(cr_files)
    if cr_total == 0:
        emit(WARN, "Code review gate: no agent-code-review sessions found for this release")
    elif cr_done == 0:
        emit(FAIL, f"Code review gate: {cr_total} session(s) dispatched but none completed "
             f"(all quarantined/needs-info) — code shipped without review")
    else:
        emit(PASS, f"Code review gate: {cr_done}/{cr_total} review(s) completed")

    # ── 6. CEO proxy load ────────────────────────────────────────────────────
    section("CEO Proxy Load")

    proxy = ceo_proxy_sessions(release_id, feature_ids, co_release_id, push_time)
    total_proxy = sum(len(v) for v in proxy.values())
    dev_proxy   = len(proxy.get("dev", []))
    qa_proxy    = len(proxy.get("qa", []))
    pm_proxy    = len(proxy.get("pm", []))
    other_proxy = len(proxy.get("other", []))

    print(f"  CEO sessions acting as dev proxy:  {dev_proxy}")
    print(f"  CEO sessions acting as QA proxy:   {qa_proxy}")
    print(f"  CEO sessions acting as PM proxy:   {pm_proxy}")
    print(f"  Other CEO sessions for release:    {other_proxy}")
    print(f"  Total CEO proxy sessions:          {total_proxy}")

    if total_proxy > THRESH_CEO_PROXY_FAIL:
        emit(FAIL, f"CEO proxy load: {total_proxy} sessions doing dev/QA/PM work "
             f"(dev={dev_proxy}, QA={qa_proxy}, PM={pm_proxy}) — executor broken or roles understaffed")
    elif total_proxy > THRESH_CEO_PROXY_WARN:
        emit(WARN, f"CEO proxy load: {total_proxy} sessions doing dev/QA/PM work "
             f"(dev={dev_proxy}, QA={qa_proxy}, PM={pm_proxy})")
    else:
        emit(PASS, f"CEO proxy load: {total_proxy} sessions — within threshold")

    # ── 7. Summary ───────────────────────────────────────────────────────────
    section("Summary")
    print(f"  Release: {release_id}")
    print(f"  Findings: {fail_count} FAIL, {warn_count} WARN, "
          f"{len(findings) - fail_count - warn_count} PASS")

    overall = FAIL if fail_count > 0 else (WARN if warn_count > 0 else PASS)
    print(f"  Overall: {overall}")

    if args.json:
        out = {
            "release_id": release_id,
            "site": site,
            "push_time": push_time.isoformat() if push_time else None,
            "features": feature_ids,
            "fail_count": fail_count,
            "warn_count": warn_count,
            "findings": [{"level": lv, "msg": m} for lv, m in findings],
            "metrics": {
                "total_dev_passes": total_passes,
                "redundant_features": redundant_features,
                "shipping_lag_hours": round(shipping_lag, 1) if shipping_lag else None,
                "r5_delay_hours": round(r5_delay, 1) if r5_delay else None,
                "quarantine_rate": round(global_rate, 3),
                "ceo_proxy_total": total_proxy,
                "ceo_proxy_dev": dev_proxy,
                "ceo_proxy_qa": qa_proxy,
                "ceo_proxy_pm": pm_proxy,
            },
        }
        print()
        print(json.dumps(out))

    # ── 8. Auto-log FAILs to issues.md ──────────────────────────────────────
    if fail_count > 0 and not args.json:
        _append_findings_to_issues(release_id, findings)

    return 1 if fail_count > 0 else 0


def _next_issue_number(issues_path: pathlib.Path) -> int:
    """Scan issues.md and return the next available ISSUE-NNN number."""
    if not issues_path.exists():
        return 1
    txt = issues_path.read_text(errors="ignore")
    nums = [int(m) for m in re.findall(r"ISSUE-(\d+)", txt)]
    return max(nums, default=0) + 1


def _append_findings_to_issues(release_id: str, findings_list: list[tuple[str, str]]) -> None:
    """
    Append FAIL-level findings from this run to issues.md as new ISSUE entries.

    Deduplication: if issues.md already contains an entry referencing this release_id
    and the same finding keyword, skip it (avoid re-logging on repeated runs).
    """
    issues_path = ROOT / "issues.md"
    if not issues_path.exists():
        return

    existing = issues_path.read_text(errors="ignore")
    already_logged = release_id in existing

    fail_findings = [(lv, msg) for lv, msg in findings_list if "FAIL" in lv]
    if not fail_findings:
        return

    if already_logged:
        # Already has an entry for this release — don't duplicate
        return

    next_num = _next_issue_number(issues_path)
    run_date = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")

    lines = [
        "",
        f"---",
        "",
        f"## Release Efficiency Findings — {release_id} — {run_date}",
        "",
        f"> **Source:** `scripts/release-efficiency-analysis.py` — automated analysis.",
        f"> {len(fail_findings)} FAIL finding(s) detected. See below for details.",
        "",
    ]

    for i, (_, msg) in enumerate(fail_findings):
        issue_num = next_num + i
        # Derive a short title from the message (up to 70 chars)
        title = msg[:70].rstrip()
        lines += [
            f"### ISSUE-{issue_num:03d} — {title}",
            "",
            f"**Severity:** High",
            f"**Release:** {release_id}",
            f"**Source:** release-efficiency-analysis.py",
            "",
            f"**Finding:** {msg}",
            "",
            "**Status:** 🔴 Open — review and assign fix",
            "",
        ]

    with issues_path.open("a") as fh:
        fh.write("\n".join(lines))
        fh.write("\n")

    print(f"\n   ℹ️   {len(fail_findings)} finding(s) appended to issues.md "
          f"(ISSUE-{next_num:03d}–ISSUE-{next_num + len(fail_findings) - 1:03d})")


if __name__ == "__main__":
    sys.exit(main())
